### ISSUE TITLE
Amendment requires

### ISSUE THREAD

**Issue by prashantherald** [JRisal01/taxcalculator#1]
Hello Jeevan Risal,
I reviewed the page you created. Everything else is good but you need to amend this few thing regarding design
1) Firstly, change the font for the title "we are here for you" with a suitable one
2) Change the colour for the text "calculate" like white on calculate button.
3) Lastly, at the button of the website decrease the size of the vector on the contact us section for location and email.

Also, add some padding on each form just like this 

.home_contact_mainPart_right .home_contact_mainPart_right_form div textarea {
    width: 100%;
    height: 150px;
    background: #F4F4F4;
    border-radius: 13px;
    border: none;
    padding: 20px;
}

**Comment by JRisal01** [comment]
Issue solved

**Comment by JRisal01** [comment]
Ok I Will change the design as per the things you mentioned above.
