### ISSUE TITLE
Issues on calculator page

### ISSUE THREAD

**Issue by prashantherald** [JRisal01/taxcalculator#14]
@JRisal01  Here are some issues I found on the calculator page 
- There is a default border in the form CSS this  in the  border: 1px solid #ccc; 
- Change the color of a button text to white.
- Adjust padding for each input form
![186018013_477385646861249_2896560193033670022_n](https://user-images.githubusercontent.com/82229204/118384079-0e012a00-b623-11eb-91cb-ef7ebf2a77b3.png)

**Comment by JRisal01** [comment]
Done
