### ISSUE TITLE
Label crossing the box

### ISSUE THREAD

**Issue by Peshal61** [JRisal01/taxcalculator#2]
Hey Jeevan, make sure that the labels are fitted on the box created in home page.It can be seen that labels are attached to the box and some letters are hidden.
![Issue1](https://user-images.githubusercontent.com/81948434/114876585-30ced180-9e1e-11eb-80e9-98d5d1446805.JPG)

**Comment by JRisal01** [comment]
Done

**Comment by Taps-star** [comment]
The issues has been solved. There was some mistakes in css. Now the problem has been solved. Thank you.
