### ISSUE TITLE
Text resizing

### ISSUE THREAD

**Issue by Peshal61** [JRisal01/taxcalculator#3]
The highightted text in the image could be made a bit smaller so that it fits around the image box.
![Issue2](https://user-images.githubusercontent.com/81948434/114877383-f580d280-9e1e-11eb-9f5d-2f5fdf4b6cec.JPG)

**Comment by JRisal01** [comment]
Done

**Comment by Taps-star** [comment]
This one is also solved. I have made the text smaller. Thank you.
