### ISSUE TITLE
Text Color

### ISSUE THREAD

**Issue by Peshal61** [JRisal01/taxcalculator#4]
The color of the highlighted text is could also be changed.
![Issue3](https://user-images.githubusercontent.com/81948434/114877845-6922df80-9e1f-11eb-80b3-296f51b1d46f.JPG)

**Comment by JRisal01** [comment]
Done

**Comment by Taps-star** [comment]
The issues has been solved, do look it once. If still you find some issues please do mentioned us. Thank you.
